import ActionPrivileges from "./actionPrivileges";
import Actions from "./actions";
import ActionsProject from "./actionsProject";
import Blob from "./blob";
import BlobMapper from "./blobMapper";
import Category from "./category";
import CategoryActions from "./categoryActions";
import CategoryHierarchy from "./categoryHierarchy";
import CategoryOption from "./categoryOption";
import CategoryOptionsLink from "./categoryOptionsLink";
import CategoryOptionsTemplate from "./categoryOptionsTemplate";
import CategoryOptionsType from "./categoryOptionsType";
import CategoryOptionsTypeTemplate from "./categoryOptionsTypeTemplate";
import City from "./city";
import CmsElementsProject from "./cmsElementsProjects";
import CmsMenuItemsPrivilegesProjects from "./cmsMenuItemsPrivilegesProjects";
import CmsMenuItemsProjects from "./cmsMenuItemsProjects";
import CmsMenuProjects from "./cmsMenuProjects";
import CmsPagePrivilegesProjects from "./cmsPagePrivilegesProjects";
import CmsPagesProjects from "./cmsPagesProjects";
import Comment from "./comments";
import Config from "./config";
import Conversation from "./conversation";
import ConversationMessages from "./conversationMessages";
import ConversationMessageMembers from "./conversationMessagesMembers";
import Country from "./country";
import Dimensions from "./dimensions";
import DimensionsProject from "./dimensionsProject";
import EsItemSync from "./esItemSync";
import Invoice from "./invoices";
import InvoiceItem from "./invoicesItems";
import InvoiceUser from "./invoicesUsers";
import Item from "./item";
import ItemCategory from "./itemCategory";
import ItemCategoryOption from "./itemCategoryOption";
import ItemCategoryOptionTerm from "./itemCategoryOptionTerm";
import ItemProcessState from "./itemProcessState";
import ItemTag from "./itemTag";
import ItemTransaction from "./itemTransaction";
import ItemTransactionCategoryOptions from "./itemTransactionCategoryOptions";
import ItemUserAction from "./itemUserAction";
import Language from "./language";
import LanguageProject from "./languageProject";
import MailParts from "./mailParts";
import MailSenders from "./mailSenders";
import MailTypes from "./mailTypes";
import MailTypesProjects from "./mailTypesProject";
import Privileges from "./privileges";
import PrivilegesProject from "./privilegesProject";
import Process from "./process";
import ProcessChain from "./processChain";
import ProcessChainActionInjection from "./processChainActionInjection";
import ProcessChainPrivilege from "./processChainPrivilege";
import ProcessChainState from "./processChainState";
import Project from "./project";
import Roles from "./roles";
import RolesProject from "./rolesProject";
import Seos from "./seos";
import Status from "./status";
import StatusActions from "./statusActions";
import StatusProjects from "./statusProjects";
import Tag from "./tag";
import Translations from "./translations";
import Users from "./user";
import UserAuths from "./userauth";
import UserConversation from "./userconversation";
import UserInvoiceValue from "./userInvoicesValue";
import UserRoles from "./userRoles";
import UserTypeRoles from "./userTypeRoles";
import UserTypes from "./userTypes";
import V_Category from "./v_category";
import vProject from "./v_project";
import vUser from "./v_user";

export interface MappsDbModels {
    Users: ReturnType<typeof Users.initModel>;
    Category: ReturnType<typeof Category.initModel>;
    CategoryHierarchy: ReturnType<typeof CategoryHierarchy.initModel>;
    BlobMapper: ReturnType<typeof BlobMapper.initModel>;
    Item: ReturnType<typeof Item.initModel>;
    ItemCategory: ReturnType<typeof ItemCategory.initModel>;
    Blob: ReturnType<typeof Blob.initModel>;
    V_User: ReturnType<typeof vUser.initModel>;
    Country: ReturnType<typeof Country.initModel>;
    City: ReturnType<typeof City.initModel>;
    UserAuths: ReturnType<typeof UserAuths.initModel>;
    CategoryOptionsType: ReturnType<typeof CategoryOptionsType.initModel>;
    CategoryOptionsTypeTemplate: ReturnType<typeof CategoryOptionsTypeTemplate.initModel>;
    CategoryOptionsTemplate: ReturnType<typeof CategoryOptionsTemplate.initModel>;
    CategoryOption: ReturnType<typeof CategoryOption.initModel>;
    CategoryOptionsLink: ReturnType<typeof CategoryOptionsLink.initModel>;
    ItemCategoryOption: ReturnType<typeof ItemCategoryOption.initModel>;
    Tag: ReturnType<typeof Tag.initModel>;
    ItemTag: ReturnType<typeof ItemTag.initModel>;
    Project: ReturnType<typeof Project.initModel>;
    Config: ReturnType<typeof Config.initModel>;
    UserTypes: ReturnType<typeof UserTypes.initModel>;
    EsItemSync: ReturnType<typeof EsItemSync.initModel>;
    Translations: ReturnType<typeof Translations.initModel>;
    Language: ReturnType<typeof Language.initModel>;
    LanguageProject: ReturnType<typeof LanguageProject.initModel>;
    Actions: ReturnType<typeof Actions.initModel>;
    ActionPrivileges: ReturnType<typeof ActionPrivileges.initModel>;
    ActionsProject: ReturnType<typeof ActionsProject.initModel>;
    CategoryActions: ReturnType<typeof CategoryActions.initModel>;
    Privileges: ReturnType<typeof Privileges.initModel>;
    PrivilegesProject: ReturnType<typeof PrivilegesProject.initModel>;
    Roles: ReturnType<typeof Roles.initModel>;
    RolesProject: ReturnType<typeof RolesProject.initModel>;
    UserRoles: ReturnType<typeof UserRoles.initModel>;
    UserTypeRoles: ReturnType<typeof UserTypeRoles.initModel>;
    DimensionsProject: ReturnType<typeof DimensionsProject.initModel>;
    Dimensions: ReturnType<typeof Dimensions.initModel>;
    V_Project: ReturnType<typeof vProject.initModel>;
    MailParts: ReturnType<typeof MailParts.initModel>;
    MailSenders: ReturnType<typeof MailSenders.initModel>;
    MailTypes: ReturnType<typeof MailTypes.initModel>;
    MailTypesProjects: ReturnType<typeof MailTypesProjects.initModel>;
    Seos: ReturnType<typeof Seos.initModel>;
    V_Category: ReturnType<typeof V_Category.initModel>;
    ItemUserAction: ReturnType<typeof ItemUserAction.initModel>;
    ItemTransactionCategoryOptions: ReturnType<typeof ItemTransactionCategoryOptions.initModel>;
    ItemTransaction: ReturnType<typeof ItemTransaction.initModel>;
    Conversation: ReturnType<typeof Conversation.initModel>;
    UserConversation: ReturnType<typeof UserConversation.initModel>;
    ConversationMessages: ReturnType<typeof ConversationMessages.initModel>;
    ConversationMessageMembers: ReturnType<typeof ConversationMessageMembers.initModel>;
    Status: ReturnType<typeof Status.initModel>;
    StatusActions: ReturnType<typeof StatusActions.initModel>;
    StatusProjects: ReturnType<typeof StatusProjects.initModel>;
    ItemCategoryOptionTerm: ReturnType<typeof ItemCategoryOptionTerm.initModel>;
    Comment: ReturnType<typeof Comment.initModel>;
    Invoice: ReturnType<typeof Invoice.initModel>;
    InvoiceUser: ReturnType<typeof InvoiceUser.initModel>;
    InvoiceItem: ReturnType<typeof InvoiceItem.initModel>;
    UserInvoiceValue: ReturnType<typeof UserInvoiceValue.initModel>;
    ProcessChain: ReturnType<typeof ProcessChain.initModel>;
    Process: ReturnType<typeof Process.initModel>;
    ProcessChainState: ReturnType<typeof ProcessChainState.initModel>;
    ItemProcessState: ReturnType<typeof ItemProcessState.initModel>;
    ProcessChainActionInjection: ReturnType<typeof ProcessChainActionInjection.initModel>;
    ProcessChainPrivilege: ReturnType<typeof ProcessChainPrivilege.initModel>;
    CmsElementsProject: ReturnType<typeof CmsElementsProject.initModel>;
    CmsMenuItemsPrivilegesProjects: ReturnType<typeof CmsMenuItemsPrivilegesProjects.initModel>;
    CmsMenuItemsProjects: ReturnType<typeof CmsMenuItemsProjects.initModel>;
    CmsMenuProjects: ReturnType<typeof CmsMenuProjects.initModel>;
    CmsPageProjects: ReturnType<typeof CmsPagesProjects.initModel>;
    CmsPagePrivilegesProjects: ReturnType<typeof CmsPagePrivilegesProjects.initModel>;
  }